#!/bin/sh

source create_ips_hls_affine_transform_id0.sh 1>create_ips_hls_affine_transform_id0.log 2>create_ips_hls_affine_transform_id0.logerr
source create_ips_hls_rgb2yuv_id0.sh 1>create_ips_hls_rgb2yuv_id0.log 2>create_ips_hls_rgb2yuv_id0.logerr
source create_ips_hls_yuv2rgb_id0.sh 1>create_ips_hls_yuv2rgb_id0.log 2>create_ips_hls_yuv2rgb_id0.logerr
